<?php
// Load translation data
$this->i18nTheme('main');
/**
 * $this->css(Pi::url('static/vendor/bootstrap/css/font-awesome.min.css'));
 * 
 * conflict with discourse.css
 */
$this->css($this->asset('module/discourse', '/css/discourse.css'));
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
<meta charset="<?php echo $charset; ?>">
<?php echo $this->headTitle(); ?>
</head>
<body class="docked">
<section id="main" class="ember-application">
<div class="ember-view">
<header id="main-header" class="ember-view d-header clearfix">
</header>
<div id="main-outlet">
<?php if (!empty($content)) echo $content; ?>
</div>
</div>
</section>
</body>
</html>